#!/usr/bin/env bash
set -e

echo "set project directory"
cd "$(dirname "$(readlink -f "$0")")"
cd ".."

export PATH="$HOME/.local/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
. $NVM_DIR/nvm.sh

echo "--> Setting node version"
nvm use

echo "Installing dependencies..."
yarn install --production=false

echo "Fetching translations..."
yarn transifex:pull

echo "Building project..."
if [ $1 = "staging" ]; then
  yarn run staging-build
else
  yarn run prod-build
fi

echo "Moving files to dist folder"
rm -rf dist
mv build dist

if grep -q ^SENTRY .env; then
  echo "Uploading source maps to sentry"
  yarn run sentry-cli sourcemaps inject ./dist
  env $(grep ^SENTRY .env | xargs) yarn run sentry-cli sourcemaps upload ./dist
else
  echo "SENTRY ENV variables not found in .env file, skipping source maps upload"
fi

echo "--> All done :)"
